### PR TITLE
Ability to read from node.js Buffer

### PR DESCRIPTION
**Pull request by moimart**
Hi,

I came across your neat library to help me get MacOS folder icons in Hyper terminal. I made it work and it's at https://github.com/moimart/hyper-folder-icon. I'd like to be able to merge my changes with your mainline.

The main change is to able to read from a Buffer, not only from a file path. While testing the changes, I found there are some entries new in MacOS that your parser still does not acknowledge. I added the ability to ignore certain entries and saw that there are new ic05 and ic06 entries which I duplicated from other existing ones. I haven't tested those entries, though.

Let me know if it needs more polishing.

Thanks!

Br,
Moises

### CODE REVIEW

**Comment by jhermsmeier** [comment]
This is great, thank you! I was planning to support parsing from straight from in memory buffers, rather than reading the file, but never got around to it.

Do you happen to have some sample .icns files with the new types I could inspect? I haven't come across them yet, and also haven't found docs on them yet. Would like to know the dimensions & format etc. of them before they're included.

**Comment by moimart** [comment]
I'm attaching the icns I created recently by using iconutil on my Mac. It contains couple of the new types.

Let me know of any issues.

Thanks!

[icons.zip](https://github.com/jhermsmeier/node-apple-icns/files/2012318/icons.zip)

**Comment by jhermsmeier** [comment]
As an aside; I realized that this module should probably not be throwing an error on an unknown type, but ignore / skip it instead, as it'll otherwise break every time Apple decides to add a new type. Not sure how that escaped my mind when writing this :D Made myself https://github.com/jhermsmeier/node-apple-icns/issues/2 to not forget this.

**Comment by moimart** [comment]
Sure. Can do. Just to be clear:

1 PR for ignoring types
2 PR for reading from buffer

is that correct?

**Comment by jhermsmeier** [comment]
Yup, that'd be really sweet! :)

**Comment by moimart** [comment]
I'm closing this as the new pull request is cleaner :)

**Pull request closed without merging**
